package Acme::CPANLists::Import::PerlAdvent::2005_12_12;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2005/12/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"HTML::FromANSI"},{module=>"Regexp::English"},{module=>"Rx"},{module=>"YAPE::Regex"},{module=>"YAPE::Regex::Explain"}],summary=>"Modules mentioned in Perl Advent Calendar 2005 (day 12)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2005 (day 12)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2005/12/> (retrieved on 2016-11-07). Visit the URL for the full contents.

