package Acme::CPANLists::Import::PerlAdvent::2005_12_07;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2005/7/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Bundle::PerlPoint"}],summary=>"Modules mentioned in Perl Advent Calendar 2005 (day 7)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2005 (day 7)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2005/7/> (retrieved on 2016-11-07). Visit the URL for the full contents.

