package Acme::CPANLists::Import::PerlAdvent::2005_12_11;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2005/11/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Perl6::Junction"},{module=>"Quantum::Superpositions"},{module=>"Set::Array"},{module=>"Set::Bag"},{module=>"Set::IntRange"},{module=>"Set::IntSpan"},{module=>"Set::Scalar"}],summary=>"Modules mentioned in Perl Advent Calendar 2005 (day 11)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2005 (day 11)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2005/11/> (retrieved on 2016-11-07). Visit the URL for the full contents.

