#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2005',
                url => "http://perladvent.org/2005/",
                extract_urls => [map {"http://perladvent.org/2005/$_/"}
                             5..25],
                summary => 'Modules mentioned in Perl Advent Calendar 2005',
            },
            {
                name => '2005_12_05',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 5)",
                url => "http://perladvent.org/2005/5/",
            },
            {
                name => '2005_12_06',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 6)",
                url => "http://perladvent.org/2005/6/",
                add_modules => ['App::XLSperl'],
            },
            {
                name => '2005_12_07',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 7)",
                url => "http://perladvent.org/2005/7/",
            },
            {
                name => '2005_12_08',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 8)",
                url => "http://perladvent.org/2005/8/",
            },
            {
                name => '2005_12_09',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 9)",
                url => "http://perladvent.org/2005/9/",
            },
            {
                name => '2005_12_10',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 10)",
                url => "http://perladvent.org/2005/10/",
            },
            {
                name => '2005_12_11',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 11)",
                url => "http://perladvent.org/2005/11/",
            },
            {
                name => '2005_12_12',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 12)",
                url => "http://perladvent.org/2005/12/",
            },
            {
                name => '2005_12_13',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 13)",
                url => "http://perladvent.org/2005/13/",
            },
            {
                name => '2005_12_14',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 14)",
                url => "http://perladvent.org/2005/14/",
            },
            {
                name => '2005_12_15',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 15)",
                url => "http://perladvent.org/2005/15/",
            },
            {
                name => '2005_12_16',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 16)",
                url => "http://perladvent.org/2005/16/",
            },
            {
                name => '2005_12_17',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 17)",
                url => "http://perladvent.org/2005/17/",
            },
            {
                name => '2005_12_18',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 18)",
                url => "http://perladvent.org/2005/18/",
            },
            {
                name => '2005_12_19',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 19)",
                url => "http://perladvent.org/2005/19/",
            },
            {
                name => '2005_12_20',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 20)",
                url => "http://perladvent.org/2005/20/",
            },
            {
                name => '2005_12_21',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 21)",
                url => "http://perladvent.org/2005/21/",
            },
            {
                name => '2005_12_22',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 22)",
                url => "http://perladvent.org/2005/22/",
            },
            {
                name => '2005_12_23',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 23)",
                url => "http://perladvent.org/2005/23/",
            },
            {
                name => '2005_12_24',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 24)",
                url => "http://perladvent.org/2005/24/",
            },
            {
                name => '2005_12_25',
                summary => "Modules mentioned in Perl Advent Calendar 2005 (day 25)",
                url => "http://perladvent.org/2005/25/",
            },
        ],
        namespace => 'Acme::CPANLists::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
